name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore StorefrontUI2/
    - name: Build
      run: dotnet build StorefrontUI2/ --configuration Release --no-restore
    - name: Test
      run: dotnet test Storetests/ --no-build --verbosity normal
  deploy:
    runs-on:ubuntu-latest
    steps:
    - name: publish
      run: dotnet publish StorefrontUI2/ --configuration Release -o ./publish
    - name: 'Run Azure webapp deploy action using publish profile credentials'
       uses: azure/webapps-deploy@v2
        with: 
          app-name: Julian-Storefront
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
